fix handler notify
nspcc-dev/ansible-goodies pull request #4
Opened 2023-09-11 00:08 UTC by 532910

2023-09-11 06:03 UTC, roman-khimov reviewed
Please fix commit message (add prefix, fix-email) and explain what's the real problem there.

2023-09-11 11:18 UTC, 532910 commented
understood nothing
the real problem that it was not work before, and now it works

2023-09-14 14:44 UTC, roman-khimov approved these changes

2023-09-14 14:44 UTC, roman-khimov requested changes
SOB doesn't match Author

2023-09-15 08:39 UTC, roman-khimov approved these changes

2023-09-15 08:39 UTC, merged